### ISSUE TITLE
iChun easter egg not working

### ISSUE THREAD

**Issue by ljcool2006** [iChun/BeeBarker#5]
The iChun easter egg is broken.
**Steps to reproduce**
1. Rename a dog to iChun
2.  Feed them a flower
3. Right click them with an empty hand
4. Hold right click
It barks out bees like the other dogs instead of barking out fire.
![2020-07-05_05 12 48](https://user-images.githubusercontent.com/51834343/86529373-3dc99800-be7e-11ea-9b1e-8d1408cb590c.png)

**Comment by iChun** [comment]
Fixed in 9.0.1. Thanks for the report!
